# Generated by Django 5.0.7 on 2025-04-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registro_visitantes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oficina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='fecha',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='hora',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='motivo_visita',
        ),
        migrations.RemoveField(
            model_name='visitante',
            name='oficina',
        ),
        migrations.AlterField(
            model_name='visitante',
            name='cedula',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.CreateModel(
            name='RegistroVisita',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('motivo_visita', models.CharField(max_length=255)),
                ('fecha_hora', models.DateTimeField(auto_now_add=True)),
                ('oficina', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='registro_visitantes.oficina')),
                ('visitante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registro_visitantes.visitante')),
            ],
        ),
    ]
